import Head from 'next/head'

export default function Downloads() {
  return (
    <div>
      <Head>
        <title>Downloads - Dagyaw Dialogues</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid w-full h-screen place-items-center">
        <h1 className="font-bold text-blue-700 text-7xl">
          to God be the glory, honor and praise!
        </h1>
      </main>
    </div>
  )
}
