import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen w-full grid place-items-center">
        <h1 className="text-7xl text-blue-700 font-bold">
          to God be the glory!
        </h1>
      </main>
    </div>
  );
}
