import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid w-full h-screen place-items-center">
        <h1 className="font-bold text-blue-700 text-7xl">
          to God be the glory, honor and praise!
        </h1>
      </main>
    </div>
  );
}
